spring:
  application:
    name: fileservice-client
server:
  port: ${PORT:8090}
eureka:
  client:
    fetchRegistry: true
    registryFetchIntervalSeconds: 5
    serviceUrl:
      defaultZone: http://fileservicediscovery:8761/eureka/
  instance:
    preferIpAddress: true
logging:
  file: logs/application.log
  level:
    root: INFO
    org.springframework.web: INFO
    de.exb.platform: INFO